# Generated by Django 4.2.16 on 2024-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahkar_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
