# Generated by Django 4.2.16 on 2024-10-17 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shahkar_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="nathinal_id",
            new_name="natoinal_id",
        ),
        migrations.AlterField(
            model_name="analyzer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
