# Generated by Django 4.2.16 on 2024-10-21 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shahkar_user', '0002_alter_userprofile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(max_length=255)),
                ('analyzer_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('phonenumber', models.CharField(db_index=True, max_length=13)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('result_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('request_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
            },
        ),
    ]
