# Generated by Django 4.2.16 on 2024-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shahkar_user", "0002_rename_nathinal_id_user_natoinal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
