version: '3.8'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"  # پورت برای ارتباطات Spark
      - "8080:8080"  # پورت برای رابط کاربری
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  # اتصال به master
    depends_on:
      - spark-master
    networks:
      - spark-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"  # پورت برای PostgreSQL
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
