version: '3.8'
services:



  postgres:
    image: postgres
    container_name: shahkar-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shahkar
    ports:
      - "5433:5432"  
    networks:
      - spark-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - spark-network

  django:
    build: .
    container_name: django_app
    environment:
      - DATABASE_URL=postgres://username:1234@postgres:5432/shahkar
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - spark-network

  celery:
    build: . 
    image: celery
    container_name: celery_worker
    command: celery --app shahkar_sample worker --concurrency=4
    depends_on:
      - django
      - redis
    networks:
      - spark-network

  
  spark-master:
    image: spark_image
    container_name: shahkar_spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"  
      - "8080:8080"  
    networks:
      - spark-network

  spark-worker:
    image: spark_image
    container_name: shahkar_spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077  
    depends_on:
      - spark-master
    networks:
      - spark-network



networks:
  spark-network:
    driver: bridge

