# global:
#   scrape_interval: 15s  

# scrape_configs:
#   - job_name: 'django'
#     static_configs:
#       - targets: ['django:8000']  

#   - job_name: 'redis'
#     static_configs:
#       - targets: ['redis:6379']  

#   - job_name: 'postgres'
#     static_configs:
#       - targets: ['postgres:5433']  

#   - job_name: 'spark-master'
#     static_configs:
#       - targets: ['spark-master:8080']  

#   - job_name: 'spark-worker'
#     static_configs:
#       - targets: ['spark-worker:8081']  
